server:
  port: ${PORT:8091}
  servlet:
    context-path: /bca


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/mineralflow/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/mineralflow

