CREATE DATABASE IF NOT EXISTS land;
GRANT ALL
ON land.* TO 'user';
GRANT SHOW
DATABASES ON *.* TO 'user';
FLUSH
PRIVILEGES;

CREATE DATABASE IF NOT EXISTS warehousing;
GRANT ALL
ON warehousing.* TO 'user';
GRANT SHOW
DATABASES ON *.* TO 'user';
FLUSH
PRIVILEGES;

CREATE DATABASE IF NOT EXISTS water;
GRANT ALL
ON water.* TO 'user';
GRANT SHOW
DATABASES ON *.* TO 'user';
FLUSH
PRIVILEGES;

CREATE DATABASE IF NOT EXISTS invoicing;
GRANT ALL
ON invoicing.* TO 'user';
GRANT SHOW
DATABASES ON *.* TO 'user';
FLUSH
PRIVILEGES;