spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    defer-datasource-initialization: true
  rabbitmq:
    listener:
      simple:
        auto-startup: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/mineralflow
